name: Publish to npm registry

on:
  workflow_dispatch:
    inputs:
      version:
        description: "version | patch | minor | major"
        required: true
        default: "patch"

jobs:
  publish:
    uses: activeprospect/github-action-workflows/.github/workflows/release.yml@master
    with:
      version: ${{ github.event.inputs.version }}
    secrets:
      NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

